#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap, and create the application...
$app = require_once __DIR__.'/bootstrap/app.php';

// Run the application...
$status = $app->handleCommand(new \Symfony\Component\Console\Input\ArgvInput);

exit($status);
